image: python:3.6

before_script:
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt
  - python -m pip install coverage flake8

django-test:
  stage: test
  script:
    - cp settings.ini.example settings.ini
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py loaddata site-fixtures.json
    - coverage run manage.py test
    - coverage report
    # - flake8
