# Generated by Django 2.1.3 on 2018-11-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(help_text='Title of the About Page.', max_length=255)),
                ('about_first_paragraph', models.TextField(blank=True, help_text='Main paragraph of the About Page.')),
                ('about_second_paragraph', models.TextField(blank=True, help_text='Second paragraph of the About Page.')),
                ('about_image', models.ImageField(blank=True, help_text='Image that appears on the About Page.', upload_to='assets')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title_short', models.CharField(help_text='Title that appears in the main menu.', max_length=255)),
                ('site_title_long', models.CharField(help_text='Title that appears in the browser tab, bookmarks and site metadata.', max_length=255)),
                ('site_description', models.CharField(help_text='Description that appears in og tags, metadata, and search engines descriptions.', max_length=255)),
                ('twitch_username', models.CharField(help_text='Twitch username for displaying video/chat on the homepage.', max_length=15)),
                ('site_favicon', models.ImageField(help_text='Icon that appears in browser tabs and bookmarks. <br>Recommended icon is up to 256x256 ICO.', upload_to='assets')),
                ('site_meta_image', models.ImageField(help_text='Image that appears when url is unfurled.<br> Recommended image is 512x512 transparent PNG.', upload_to='assets')),
                ('site_meta_image_type', models.CharField(help_text='Valid image mime type. Ex: PNG uses: image/png', max_length=255)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Used for the alternative text for the resource.', max_length=255)),
                ('enabled', models.BooleanField(default=False, help_text='Must be checked to show up on the site.')),
                ('url', models.URLField(blank=True, help_text='Full URL that the user will be taken to on click.')),
                ('icon', models.CharField(help_text='Path to existing icon or full URL to remote icon.<br> Recommended icons are 512x512 transparent PNGs.', max_length=255)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social',
            },
        ),
    ]
