# Generated by Django 2.1.5 on 2019-01-22 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Twitch Client ID.', max_length=30)),
                ('client_secret', models.CharField(help_text='Twitch Application Secret.', max_length=30)),
                ('redirect_uri', models.URLField(help_text='Redirect URL back to this site.<br> Should contain this URI: /oauth/callback/')),
                ('response_type', models.CharField(help_text='This should almost always be: code', max_length=255)),
                ('grant_type', models.CharField(help_text='This should almost always be: authorization_code', max_length=255)),
                ('scope', models.CharField(help_text='You at least need: user_read', max_length=255)),
            ],
            options={
                'verbose_name': 'Oauth',
                'verbose_name_plural': 'Oauth',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False, max_length=80)),
                ('twitch_id', models.IntegerField(blank=True, default=0)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
